sudo: required
services:
  - docker

before_install:
  - docker build -t mitasych/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true mitasych/docker-react-udemy npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env-2"
  bucket_name: "elasticbeanstalk-eu-central-1-576219082606"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key:
    secure: "$AWS_SECRET_KEY"