sudo: required
services:
  - docker

before_install:
  - docker build -t mitasych/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true mitasych/docker-react-udemy npm run test -- --coverage