FROM node:16-alpine

RUN mkdir /app && chown node:node /app
WORKDIR '/app'

COPY package.json .

RUN npm install
RUN chown node:node /app/node_modules

COPY --chown=node:node . .

CMD [ "npm", "run", "start" ]